### ISSUE TITLE
Why are the file types arrays?

### ISSUE THREAD

**Issue by duhowise** [devpaulmensah/fileuploader#2]
`public IFormFile[] Passports { get; set; } = Array.Empty<IFormFile>();
   public IFormFile[] GhanaCard { get; set; } = Array.Empty<IFormFile>();
    public IFormFile[] VotersId { get; set; } = Array.Empty<IFormFile>();
    public IFormFile[] Nhis { get; set; } = Array.Empty<IFormFile>();
    public IFormFile[] BirthCertificates { get; set; } = Array.Empty<IFormFile>();`

Each loan request demands one of each of these files, any reason why you are passing them off as arrays?

**Comment by paul-mensah** [comment]
Request has been updated to accept one of each document type
